spring:
  application:
    name: SoundItOut
    isAlphaMode: true
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    jdbc-url: ${SPRING_DATASOURCE_JDBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    database-platform: io.github.jhipster.domain.util.FixedPostgreSQL82Dialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        generate_statistics: false
        id.new_generator_mappings: true
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
        create_empty_composites.enabled: true
        show_sql: true
        format_sql: true
  security:
    jwt:
      secret: ${JWT_SECRET}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    from: nick@sounditout.app
open-ai:
  api-key: ${OPENAI_API_KEY}
  model: gpt-3.5-turbo
microsoft:
  computer-vision:
    subscription-key: ${MICROSOFT_COMPUTER_VISION_SUBSCRIPTION_KEY}
    endpoint: https://sounditout-image-captioner.cognitiveservices.azure.com/
