spring:
  application:
    name: SoundItOut
    isAlphaMode: true
  datasource:
    jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  security:
    jwt:
      
  sendgrid:
    
  open-ai:
    
  microsoft:
    computer-vision:
      
  sql:
    init:
      schema-locations: classpath:schema-h2.sql
      mode: always