spring:
  application:
    name: SoundItOut
    isAlphaMode: true
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/sounditout
    username: sounditout
    password: SoundItOut123!
  security:
    jwt:
      
  sendgrid:
    
  open-ai:
    
  microsoft:
    computer-vision:
      