spring:
  application:
    name: SoundItOut
    isAlphaMode: true
  datasource:
    driverClassName: org.postgresql.Driver
    jdbc-url: ${SPRING_DATASOURCE_JDBC_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  sql:
    init:
      platform: postgres
  session:
    jdbc:
      table-name: SPRING_SESSION
      initialize-schema: always
  jpa:
    database-platform: io.github.jhipster.domain.util.FixedPostgreSQL82Dialect
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        generate_statistics: false
        id.new_generator_mappings: true
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
        create_empty_composites.enabled: true
        show_sql: true
        format_sql: true
  security:
    jwt:
      secret: ${JWT_SECRET}
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    fromEmail: nick@sounditout.app
    fromName: SoundItOut
    confirmEmailTemplate: "d-fbb4a70adf284346b45e7b833b73816f"
    confirmEmailBaseUrl: "https://sounditout.app"
    forgotPasswordTemplate: "d-5422a81b6fdb40a1a5b3547d56f12a63"
    forgotPasswordBaseUrl: "https://sounditout.app"
  open-ai:
    api-key: ${OPENAI_API_KEY}
    model: gpt-3.5-turbo
  microsoft:
    computer-vision:
      subscription-key: ${MICROSOFT_COMPUTER_VISION_SUBSCRIPTION_KEY}
      endpoint: https://sounditout-image-captioner.cognitiveservices.azure.com/

