spring:
  application:
    name: SoundItOut
  datasource:
    platform: postgres
    driverClassName: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/echocap
    username: echocap
    password: EchoCap123!
  jpa:
    database-platform: io.github.jhipster.domain.util.FixedPostgreSQL82Dialect
    database: POSTGRESQL
    show-sql: false
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    properties:
      hibernate:
        generate_statistics: false
        id.new_generator_mappings: true
        jdbc.batch_size: 1000
        order_inserts: true
        order_updates: true
        create_empty_composites.enabled: true
#                show_sql: true
#                format_sql: true
  security:
    jwt:
      secret: 
    oauth2:
      client:
        registration:
          cognito:
            clientId: 6an5knq5f1uv3utcpj3s3mgu8a
            clientSecret: 
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: EchoCap
        provider:
          cognito:
            issuerUri: https://cognito-idp.ap-southeast-2.amazonaws.com/ap-southeast-2_kafumYAea
            user-name-attribute: cognito:username