databaseChangeLog:
  - changeSet:
      id: 19
      author: nickmarko
      changes:
        - sqlFile:
            path: seed/applicationuser.sql
            relativeToChangelogFile: true
            splitStatements: true
            stripComments: true